"""Console help text."""

from __future__ import annotations

CONSOLE_HELP_LINES = [
    "PFE Console slash commands:",
    "/help - show this help",
    "/status - show the full status formatter",
    "/status compact - show a shorter status digest",
    "/sum - alias for /status compact",
    "/ops - show the operations console digest",
    "/os - alias for /ops",
    "/ops dashboard - show the operations dashboard digest",
    "/dash - alias for /ops dashboard",
    "/ops dash - alias for /ops dashboard",
    "/ops alerts - show the operations alerts digest",
    "/alerts - alias for /ops alerts",
    "/ops policy - show the operations alert policy digest",
    "/policy - alias for /ops policy",
    "/ops pol - alias for /ops policy",
    "/trigger - show the auto-train trigger summary",
    "/trig - alias for /trigger summary",
    "/gate - show the auto-train gate summary",
    "/runtime - show the runtime stability summary",
    "/rt - alias for /runtime summary",
    "/event stream - show the operations event stream digest",
    "/event - alias for /event stream",
    "/do - run the primary focus action when it is unambiguous",
    "/see - open the primary focus inspection view",
    "/promote [note] - promote the current candidate when available",
    "/archive [note] - archive the current candidate when available",
    "/approve [note] - approve the next queued review item",
    "/reject [note] - reject the next queued review item",
    "/approve <id> [note] - approve a specific queue item by id",
    "/reject <id> [note] - reject a specific queue item by id",
    "/process - process the next queued train item",
    "/batch - process the next train queue batch",
    "/until-idle - process train queue until idle",
    "/retry - retry the current auto-train trigger evaluation",
    "/trigger-train - alias for /retry, trigger training when threshold is met",
    "/train - alias for /trigger-train, trigger training when threshold is met",
    "/dpo - run DPO training from signals",
    "/generate <scenario> [style] - generate cold-start samples",
    "/rollback [version] - rollback to a previous adapter version",
    "/reset - reset the auto-train trigger state",
    "/recover daemon - recover the worker daemon",
    "/force-recovery - force runtime recovery",
    "/restart daemon - restart the worker daemon",
    "/stop daemon - stop the worker daemon",
    "/start daemon - start the worker daemon",
    "/stop runner - stop the worker runner",
    "/doctor - show doctor output for this session",
    "/eval - trigger evaluation",
    "/distill - run distillation",
    "/serve - show serve preview for this session",
    "/candidate - show candidate timeline",
    "/cand - alias for /candidate summary",
    "/cand sum - alias for /candidate summary",
    "/cand tl - alias for /candidate timeline",
    "/cand hist - alias for /candidate history",
    "/candidate timeline - show candidate timeline explicitly",
    "/candidate history - show candidate history",
    "/candidate summary - show the candidate summary",
    "/queue - show the train queue summary",
    "/qs - alias for /queue summary",
    "/queue summary - show the train queue summary",
    "/queue sum - alias for /queue summary",
    "/queue hist - alias for /queue history",
    "/queue history - show train queue history",
    "/runner - show the worker runner summary",
    "/rs - alias for /runner summary",
    "/runner summary - show the worker runner summary",
    "/runner sum - alias for /runner summary",
    "/runner tl - alias for /runner timeline",
    "/runner timeline - show the worker runner timeline",
    "/runner hist - alias for /runner history",
    "/daemon - show worker daemon status",
    "/ds - alias for /daemon summary",
    "/daemon sum - alias for /daemon summary",
    "/daemon tl - alias for /daemon timeline",
    "/daemon history - show worker daemon history",
    "/daemon hist - alias for /daemon history",
    "/daemon summary - show the daemon summary",
    "/daemon timeline - show the worker daemon timeline",
    "/runner history - show worker runner history",
    "/settings - show current console session settings",
    "/workspace <name> - switch the workspace for this session",
    "/model <id> - change the chat model for this session",
    "/adapter <version> - change the adapter for this session",
    "/list - list adapter versions",
    "/temperature <value> - change chat temperature for this session",
    "/max-tokens <n|auto> - change chat max tokens for this session",
    "/real-local on|off - toggle real local inference for chat",
    "/refresh <seconds> - change sidebar refresh cadence",
    "/chat - switch to chat mode",
    "/cmd - switch to command mode",
    "/mode chat|command - switch input mode explicitly",
    "/like - accept the previous assistant response",
    "/dislike - reject the previous assistant response",
    "/fix <text> - submit edited version of the previous response",
    "/again - request regeneration of the previous response",
    "/clear - clear the local console transcript",
    "/quit - exit interactive mode",
    "",
    "Plain text input uses the local chat_completion pipeline.",
]


def console_help_text() -> str:
    return "\n".join(CONSOLE_HELP_LINES)


__all__ = ["CONSOLE_HELP_LINES", "console_help_text"]
