"""Prada-style difference-aware distillation utilities.

Reference: Prada paper — only distill samples where teacher and local model
differ significantly, to improve sample efficiency.
"""

from __future__ import annotations

from difflib import SequenceMatcher
from typing import Optional


def compute_text_similarity(a: str, b: str) -> float:
    """Compute similarity between two texts.

    Uses SequenceMatcher (same underlying approach as dataset deduplication)
    to avoid introducing heavy new dependencies. Returns a float between 0 and 1.
    """
    if not a.strip() or not b.strip():
        return 0.0
    return SequenceMatcher(None, a.strip(), b.strip()).ratio()


def should_use_teacher_output(
    local_output: str,
    teacher_output: str,
    threshold: float = 0.85,
) -> tuple[bool, float]:
    """Decide whether the teacher sample is worth keeping.

    Args:
        local_output: Output from the local (student) model.
        teacher_output: Output from the teacher model.
        threshold: Similarity threshold above which the sample is discarded.

    Returns:
        (use_teacher, similarity) where use_teacher is True if the teacher
        output differs enough from the local output to be valuable.
    """
    similarity = compute_text_similarity(local_output, teacher_output)
    return similarity < threshold, similarity


def should_use_teacher_output_for_user_preference(
    teacher_output: str,
    user_edited_text: str,
    similarity_threshold: float = 0.7,
) -> tuple[bool, float]:
    """Difference-driven gate for teacher distillation aligned with user preference.

    Only accept the teacher output when it is *sufficiently similar* to the
    user-edited text (above ``similarity_threshold``).  High similarity means
    the teacher understood the user's preference direction; low similarity means
    the teacher is off-target and the sample should be discarded.

    Args:
        teacher_output: Output generated by the teacher model.
        user_edited_text: The user's edited / preferred text.
        similarity_threshold: Minimum similarity required to keep the teacher sample.

    Returns:
        (use_teacher, similarity) where ``use_teacher`` is True when the teacher
        output aligns with the user preference direction.
    """
    similarity = compute_text_similarity(teacher_output, user_edited_text)
    return similarity >= similarity_threshold, similarity
