"""Teacher signal fusion: merge user signals with teacher-distilled samples."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional, Sequence

from .datasets import _get_attr, _normalize_text, _similarity


@dataclass
class TeacherSignalFusionConfig:
    """Configuration for teacher signal fusion."""

    max_teacher_ratio: float = 0.3
    similarity_threshold: float = 0.7
    user_signal_priority: bool = True


def _sample_key_text(sample: Any) -> str:
    instruction = _normalize_text(_get_attr(sample, "instruction", ""))
    chosen = _normalize_text(_get_attr(sample, "chosen", ""))
    rejected = _normalize_text(_get_attr(sample, "rejected", ""))
    return f"{instruction}|{chosen}|{rejected}"


def _has_user_signal_for_prompt(user_signals: Sequence[Any], instruction: str) -> bool:
    norm_instruction = _normalize_text(instruction)
    for sig in user_signals:
        if _normalize_text(_get_attr(sig, "instruction", "")) == norm_instruction:
            return True
    return False


def _has_user_edit_for_prompt(user_signals: Sequence[Any], instruction: str) -> bool:
    norm_instruction = _normalize_text(instruction)
    for sig in user_signals:
        if _normalize_text(_get_attr(sig, "instruction", "")) == norm_instruction:
            reply_style = _get_attr(sig, "reply_style", None)
            if reply_style is None:
                metadata = _get_attr(sig, "metadata", {})
                reply_style = metadata.get("reply_style") if isinstance(metadata, dict) else None
            if reply_style == "edited":
                return True
    return False


class TeacherSignalFusion:
    """Fuse user signals with teacher-generated samples.

    Strategy:
    - User signals (accept/edit/reject) always take priority over teacher signals.
    - Teacher samples are only used to supplement domains/styles not covered by user signals.
    - If the same prompt has both a user edit and a teacher suggestion, the user edit wins.
    - Teacher samples are capped at ``max_teacher_ratio`` of the total fused dataset.
    - Every teacher sample carries provenance metadata so its origin is auditable.
    """

    def __init__(self, config: Optional[TeacherSignalFusionConfig] = None) -> None:
        self.config = config or TeacherSignalFusionConfig()

    def fuse_signals(
        self,
        user_signals: Sequence[Any],
        teacher_signals: Sequence[Any],
    ) -> list[Any]:
        """Merge user and teacher signals according to the fusion strategy.

        Args:
            user_signals: Samples derived from real user feedback.
            teacher_signals: Samples generated by the teacher model.

        Returns:
            A list of fused samples with teacher provenance preserved.
        """
        fused: list[Any] = list(user_signals)
        user_keys = {_sample_key_text(s) for s in user_signals}

        # Filter teacher signals that duplicate user-covered prompts or have user edits
        candidate_teacher: list[Any] = []
        for ts in teacher_signals:
            key = _sample_key_text(ts)
            if key in user_keys:
                continue
            instruction = _get_attr(ts, "instruction", "")
            if self.config.user_signal_priority and _has_user_signal_for_prompt(user_signals, instruction):
                continue
            candidate_teacher.append(ts)

        # Cap teacher ratio relative to the final fused total.
        # teacher / (user + teacher) <= max_teacher_ratio  =>  teacher <= user * max / (1 - max)
        total_user = len(user_signals)
        if total_user == 0:
            max_teacher = len(candidate_teacher)
        else:
            max_teacher = max(0, int(total_user * self.config.max_teacher_ratio / (1 - self.config.max_teacher_ratio)))
            if max_teacher == 0 and self.config.max_teacher_ratio > 0:
                # Ensure at least one teacher sample can be selected when ratio is non-zero
                max_teacher = 1

        selected_teacher = candidate_teacher[:max_teacher]
        fused.extend(selected_teacher)

        # Update dataset plan metadata on the returned list (caller can attach)
        self._last_fusion_plan = {
            "user_count": total_user,
            "teacher_candidates": len(candidate_teacher),
            "teacher_selected": len(selected_teacher),
            "total_fused": len(fused),
            "teacher_ratio": round(len(selected_teacher) / len(fused), 4) if fused else 0.0,
            "max_teacher_ratio": self.config.max_teacher_ratio,
        }
        return fused

    def get_last_plan(self) -> dict[str, Any]:
        """Return metadata about the most recent fusion operation."""
        return getattr(self, "_last_fusion_plan", {})


__all__ = [
    "TeacherSignalFusion",
    "TeacherSignalFusionConfig",
]
